name: TED monster scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "22 2 * * *"  # daily @ 02:22 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    env:
      TED_SEARCH_URL: "https://ted.europa.eu/en/advanced-search?search-txt=&published=90&nature-of-contract=all&language=en"
      TED_MAX_PAGES: "50"
      TED_MAX_NOTICES: "2000"
      YEAR: "2025"
      START_ID: "636180"
      END_ID: "635940"
      MAX_MISS: "300"
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PGSSLMODE: "require"
      PLAYWRIGHT_BROWSERS_PATH: "0"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm install
          npx playwright install --with-deps

      - name: Scrape XML (throttled)
        run: |
          node -v
          mkdir -p data/raw data/parsed tools/saxon
          TED_MAX_PAGES=$TED_MAX_PAGES TED_MAX_NOTICES=$TED_MAX_NOTICES TED_SEARCH_URL="$TED_SEARCH_URL" npm run scrape || true

      - name: Setup Saxon (download jars)
        run: |
          mkdir -p tools/saxon
          curl -sSL -o tools/saxon/saxon-he.jar https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/12.5/Saxon-HE-12.5.jar
          curl -sSL -o tools/saxon/xmlresolver.jar https://repo1.maven.org/maven2/org/xmlresolver/xmlresolver/5.2.2/xmlresolver-5.2.2.jar
          test -s tools/saxon/saxon-he.jar && test -s tools/saxon/xmlresolver.jar

      - name: Fallback sweep (recent IDs)
        run: |
          COUNT=$(ls -1 data/raw/*.xml 2>/dev/null | wc -l || true)
          echo "XML files so far: $COUNT"
          if [ "$COUNT" -eq 0 ]; then
            echo "No XML from search; running fallback brute-force sweep..."
            YEAR="$YEAR" START_ID="$START_ID" END_ID="$END_ID" MAX_MISS="$MAX_MISS" node src/bruteforce_ids.mjs
          else
            echo "Skipping fallback; we already have files."
          fi

      - name: Ingest to Postgres
        run: NODE_TLS_REJECT_UNAUTHORIZED=0 npm run ingest
